# Generated by Django 5.0.6 on 2024-06-24 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=250, null=True)),
                ('level', models.CharField(max_length=250)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('demo_video', models.FileField(blank=True, null=True, upload_to='videos/demo_video')),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='videos/thumbnails')),
                ('benefit1', models.CharField(blank=True, max_length=250, null=True)),
                ('benefit2', models.CharField(blank=True, max_length=250, null=True)),
                ('benefit3', models.CharField(blank=True, max_length=250, null=True)),
                ('original_price', models.CharField(max_length=250)),
                ('offer_price', models.CharField(max_length=250)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('reject_reason', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
