# Generated by Django 5.0.6 on 2024-07-19 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_communitychatmessages_community'),
        ('teachers', '0003_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='teachers.course'),
        ),
    ]
